workdir: ["workdir_ukbb", "workdir_vn"]

inputs:
    list_sumstats: ["ukbb_sumstats.parquet", "VN_data_samples/seed_0/VN_train_sumstats.ss"] # List all sumstats. The first one is the main one
    finemap_ss: ["ukbb_sumstats.parquet"] # Set the sumstats to use finemapping. Currently support only polyfun
    test_prefix: "VN_data_samples/seed_0/test_data_VN"
    validation_prefix: "VN_data_samples/seed_0/val_data_VN"
    phenotype_test: "VN_data_samples/seed_0/test.phenotype"
    phenotype_validation: "VN_data_samples/seed_0/validation.phenotype"
    trait_col: "Height"
    prs_method: "SCORESUM"

preprocessing:
    n_components: 6

methods:
    clumping: 
        clump_p1: 1
        clump_r2: 0.5
        clump_kb: 250
    double_weight:
        top_choice: 100000
    # polyfun:
    #     N: None
    #     use_col: "BETA"
    #     ref_dir: None
    #     max_num_causal: 2
    # prscs:
    #     use_col: "BETA"
    #     ldref_dir: "LD_REF PATH"
    #     N: 200000
    #     phi: 0.001
    # prscsx: # Only work with multiple sumstats
    #     use_col: "BETA"
    #     ldref_dir: "LD_REF PATH"
    #     N: 200000
    #     phi: 0.001

metrics:
    - coef_squared # Only for continous phenotype
    # - f1_score # Only for descrete phenotype
    # - auc_roc # Only for descrete phenotype

visualization:
    bar_plot: 
        figsize: (20, 15)
        cmap: "Dark2"



