from .clumping import clumping
from .double_weight import double_weight
from .prscs import prscs
from .ldpred import ldpred
from .SBayesS import SBayesS
from .SBayesR import SBayesR
from .polyfun import polyfun
from .ldpred2 import ldpred2
from . import multipop
